# Generated by Django 5.2.7 on 2025-11-20 09:33

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "user_identifier",
                    models.CharField(
                        db_index=True,
                        help_text="User email, username, or IP address",
                        max_length=255,
                    ),
                ),
                ("year", models.IntegerField(db_index=True, help_text="Year of usage")),
                ("month", models.IntegerField(db_index=True, help_text="Month of usage (1-12)")),
                ("total_tokens", models.IntegerField(default=0)),
                ("transformer_calls", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Token usage",
                "verbose_name_plural": "Token usages",
                "ordering": ["-year", "-month", "user_identifier"],
                "unique_together": {("user_identifier", "year", "month")},
            },
        ),
    ]
