# Generated by Django 5.2.7 on 2025-12-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_mcp_rate_limits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenusage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
