# Generated by Django 5.0.14 on 2025-05-30 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_ai_langkit_slack", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackaichatmessage",
            name="output_slack_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slack_ai_chat_message_from_output_slack_event",
                to="baseapp_ai_langkit_slack.slackevent",
            ),
        ),
    ]
