# Generated by Django 5.0.11 on 2025-03-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_ai_langkit_vector_stores", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="defaultvectorstore",
            index=models.Index(fields=["name"], name="baseapp_ai_langkit_ve_name_c2372c_idx"),
        ),
    ]
