# Generated by Django 5.2 on 2025-04-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_ai_langkit_vector_stores", "0002_defaultvectorstore_llm_chat_ve_name_c2372c_idx"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="defaultvectorstore",
            new_name="baseapp_ai__name_9fa00d_idx",
            old_name="baseapp_ai_langkit_ve_name_c2372c_idx",
        ),
    ]
