# Generated by Django 5.0.14 on 2025-06-18 20:06

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseapp_ai_langkit_vector_stores",
            "0003_rename_baseapp_ai_langkit_ve_name_c2372c_idx_baseapp_ai__name_9fa00d_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultVectorStoreTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "vector_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="baseapp_ai_langkit_vector_stores.defaultvectorstore",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
