# Generated by Django 5.2.12 on 2026-04-24 19:47

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def warn_deprecated_permission_model(apps, schema_editor):  # noqa: ARG001
    logger.warning(
        "The BASEAPP_AI_LANGKIT_MCP_TOOL_PERMISSION_MODEL setting has been deprecated and removed. "
        "MCP tool access is now controlled by three built-in permissions: "
        "access_standard_mcp_tools, access_debug_mcp_tools, and access_experimental_mcp_tools. "
        "All permissions created by your previous MCPToolPermission subclass migration can be safely deleted manually."
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPToolPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("access_standard_mcp_tools", "Can access standard MCP tools"),
                    ("access_debug_mcp_tools", "Can access debug MCP tools"),
                    ("access_experimental_mcp_tools", "Can access experimental MCP tools"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.RunPython(warn_deprecated_permission_model, migrations.RunPython.noop),
    ]
