# Generated by Django 5.2.7 on 2025-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_mcp_logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcplog",
            name="completion_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mcplog",
            name="prompt_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mcplog",
            name="total_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mcplog",
            name="transformer_calls",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mcplog",
            name="user_identifier",
            field=models.CharField(
                blank=True,
                help_text="User email, username, or IP address",
                max_length=255,
                null=True,
            ),
        ),
    ]
