# Generated by Django 5.2.7 on 2025-12-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_mcp_logs", "0002_mcplog_completion_tokens_mcplog_prompt_tokens_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcplog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
