# Generated by Django 5.2.4 on 2025-08-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_ai_langkit_chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatprepromptedquestion",
            name="prompt",
            field=models.TextField(
                help_text="Text shown in the user input when a pre-prompt is selected. This is the prompt that will be sent to the LLM."
            ),
        ),
    ]
