# Generated by Django 5.0.10 on 2025-02-14 15:26

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_ai_langkit_chats", "0002_chatidentity_alter_chatsession_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatPrePromptedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the pre-prompted question, shown in the dropdown for users to select.",
                        max_length=255,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="Text shown in the user input when a pre-prompt is selected. This is the prompt that will be sent to the LLM.",
                        max_length=400,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Chat Pre-Prompted Question",
                "verbose_name_plural": "Chat Pre-Prompted Questions",
            },
        ),
    ]
