# Generated by Django 5.2.12 on 2026-05-11 18:37

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp_ai_langkit_runners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMRunnerTopologyLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "node_positions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON map: { node_key: { x: number, y: number } } persisting per-node positions in the topology graph view.",
                    ),
                ),
                (
                    "runner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topology_layout",
                        to="baseapp_ai_langkit_runners.llmrunner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topology layout",
                "verbose_name_plural": "Topology layouts",
            },
        ),
    ]
