name: Project Workflow

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      app_name:
        required: false
        type: string

jobs:
  project-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        django-version: ["4.2.15", "5.0.8"]
    steps:
      - uses: actions/checkout@v4

      - name: Debug variables
        run: |
          echo "USERNAME=${{ vars.HARBOR_USERNAME }}"
          echo "TOKEN SET=${{ secrets.HARBOR_TOKEN != '' }}"

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: registry.tsl.io
          username: ${{ vars.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: docker compose build
        run: docker compose build --build-arg "PYTHON_VERSION=${{ matrix.python-version }}"

      - name: docker compose up
        run: docker compose up -d

      - name: flake8
        id: flake8
        run: docker compose exec web flake8 ./${{ inputs.project }} --show-source --statistics --count

      - name: isort
        id: isort
        if: steps.flake8.outcome == 'success'
        run: docker compose exec web isort --check ./${{ inputs.project }}

      - name: black
        id: black
        if: steps.isort.outcome == 'success'
        run: docker compose exec web black --check ./${{ inputs.project }}

      - name: pytest
        run: |
          app_name=$(echo "${{ inputs.project }}" | tr '-' '_')
          if [ "${{ inputs.app_name }}" ]
          then
            app_name="${{ inputs.app_name }}"
          else
            app_name=$(echo "${{ inputs.project }}" | tr '-' '_')
          fi
          tests_path="${{ inputs.project }}/${app_name}/tests"
          docker compose exec web pytest ${tests_path}

      - name: docker compose down
        run: docker compose down --volumes --remove-orphans
