name: Publish Workflow Test

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  publish-workflow:
    runs-on: ubuntu-latest
    environment: testing
    if: contains(github.event.release.tag_name, inputs.project)
    strategy:
      matrix:
        python-version: ["3.8"]

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build distribution
        working-directory: ${{ inputs.project }}
        run: python3 setup.py sdist

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ${{ inputs.project }}/dist/
