name: SonarCloud Scan

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check for changes in the repository
      id: check_changes
      run: |
        # Get a list of all files changed in this PR
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
        CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD)
        
        echo "Changed files: $CHANGED_FILES"
        
        if [ -n "$CHANGED_FILES" ]; then
          echo "run_tests=true" >> $GITHUB_ENV
        else
          echo "run_tests=false" >> $GITHUB_ENV
        fi
    - name: SonarCloud Scan
      if: env.run_tests == 'true'
      uses: SonarSource/sonarqube-scan-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=silverlogic
          -Dsonar.projectKey=silverlogic_baseapp-ai-langkit
