# Generated by Django 5.2.12 on 2026-03-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0002_examplehtmlembeddable"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPToolPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "testproject.apps.example.mcp_tools.ExampleTool1",
                        "MCP Tool Access testproject.apps.example.mcp_tools.ExampleTool1",
                    ),
                    (
                        "testproject.apps.example.mcp_tools.ExampleTool2",
                        "MCP Tool Access testproject.apps.example.mcp_tools.ExampleTool2",
                    ),
                    (
                        "testproject.apps.example.mcp_tools.ExampleTool3",
                        "MCP Tool Access testproject.apps.example.mcp_tools.ExampleTool3",
                    ),
                ],
                "abstract": False,
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
