# Generated by Django 5.2.12 on 2026-04-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0003_mcptoolpermission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MCPToolPermission",
        ),
    ]
